### ISSUE TITLE
emacs daemon: void-variable acm-frame

### ISSUE THREAD

**Issue by sawyerzheng** [twlz0ne/acm-terminal#6] opened 2023-01-06 01:23 UTC
1. emacs daemon start without acm-terminal, ` lsp-bridge-popup-complete-menu` command works OK.

2. emacs daemon start without acm-terminal, ` lsp-bridge-popup-complete-menu` produce error:
```
Debugger entered--Lisp error: (void-variable acm-frame)
  acm-terminal-update()
  apply(acm-terminal-update nil)
  acm-update()
  lsp-bridge-popup-complete-menu()
  funcall-interactively(lsp-bridge-popup-complete-menu)
  command-execute(lsp-bridge-popup-complete-menu)

```

**Comment by twlz0ne** [comment] 2023-01-09 09:37
Duplicate of https://github.com/twlz0ne/acm-terminal/issues/5

**Comment by sawyerzheng** [comment] 2023-01-10 03:45
the problem fixed

**Closed as completed** 2023-01-10 03:46 UTC
Labels: duplicate
